dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"

addons:
  sonarcloud:
    organization: "likithjoel-github"
    token:
      secure: "822192a8557b556547e4f15e138dff363dc3304f"


script:
  - sonar-scanner
  - npm test